/* ORVIA Estate Golden Master v1.0.0 — shared public shell */
(function(){
  if(typeof document==='undefined'||document.documentElement.dataset.orviaEstateV2==='1')return;
  document.documentElement.dataset.orviaEstateV2='1';
  const rewrites=[["foundation.orvia.org.uk","orviafoundation.org.uk"]];
  const products=[
    ['Human + Memory',[['MIA','https://mialegacy.uk']]],
    ['Communication',[['Voice','https://orviavoice.co.uk']]],
    ['Evidence + Decisions',[['Witness Room','https://witnessroom.co.uk'],['Threshold','https://threshold-review.co.uk'],['Insight','https://orviainsight.co.uk']]],
    ['Business',[['Web','https://orviaweb.co.uk'],['Business','https://orviabusiness.co.uk']]],
    ['Security + Operations',[['Security','https://orviasecurity.co.uk'],['Overwatch','https://orvia-overwatch.orvia.org.uk']]],
    ['Learning + Public Benefit',[['Foundation','https://orviafoundation.org.uk'],['Academy','https://academy.orvia.org.uk']]]
  ];
  document.querySelectorAll('a[href]').forEach(a=>{try{const u=new URL(a.href,location.href);rewrites.forEach(([o,n])=>{if(u.hostname===o){u.hostname=n;a.href=u.toString();}});if(u.hostname==='command.orvia.org.uk'||u.hostname==='workspace.orvia.org.uk')a.remove();}catch{}});
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{let t=n.nodeValue||'';rewrites.forEach(([o,nn])=>{t=t.split(o).join(nn);});t=t.replace(/\s*[·|]\s*ICO\s*(?:Registration\s*)?ZC152311/gi,'').replace(/ICO\s*(?:Registration\s*)?ZC152311/gi,'');n.nodeValue=t;});
  const s=document.createElement('style');s.textContent=`
  .orvia-estate-v1{font-family:Arial,Helvetica,sans-serif;background:#FAF7F2;color:#0B2450;border-bottom:1px solid rgba(11,36,80,.12);position:relative;z-index:9999}.orvia-estate-v1__inner{max-width:1240px;margin:auto;min-height:46px;padding:7px 20px;display:flex;align-items:center;gap:18px;font-size:13px}.orvia-estate-v1 a{color:#0B2450;text-decoration:none}.orvia-estate-v1__brand{font-weight:900;letter-spacing:.14em}.orvia-estate-v1__product{font-weight:700}.orvia-estate-v1 details{position:relative}.orvia-estate-v1 summary{cursor:pointer;list-style:none;font-weight:800}.orvia-estate-v1 summary::-webkit-details-marker{display:none}.orvia-estate-v1 summary:after{content:"  ▾";font-size:10px}.orvia-estate-v1 details[open] summary:after{content:"  ▴"}.orvia-estate-v1__mega{position:absolute;top:32px;left:0;width:min(760px,90vw);display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:16px;background:#fff;border:1px solid #dce4eb;border-radius:18px;box-shadow:0 24px 60px rgba(11,36,80,.16)}.orvia-estate-v1__mega section{padding:8px}.orvia-estate-v1__mega small{display:block;color:#2B929D;font-weight:900;letter-spacing:.08em;margin-bottom:7px}.orvia-estate-v1__mega a{display:block;padding:6px 0;font-weight:700}.orvia-estate-v1__push{margin-left:auto;display:flex;gap:14px;align-items:center}
  .orvia-trust-panel{font-family:Arial,Helvetica,sans-serif;background:#fff;padding:68px 0 26px;border-top:1px solid rgba(11,36,80,.08)}.orvia-trust-panel__inner{max-width:1240px;margin:auto;padding:0 20px}.orvia-trust-panel__intro{max-width:900px;margin-bottom:30px}.orvia-trust-panel__eyebrow{font-size:12px;letter-spacing:.18em;font-weight:900;color:#2B929D;margin-bottom:12px}.orvia-trust-panel h2{margin:0 0 12px;color:#0B2450;font-size:clamp(36px,5vw,72px);line-height:.98;letter-spacing:-.04em}.orvia-trust-panel__intro p{color:#5b6776;line-height:1.6}.orvia-trust-panel__grid{display:grid;grid-template-columns:1.1fr .95fr 1.2fr 1.1fr 1.1fr;border:1px solid #dce4eb;border-radius:22px;overflow:hidden;box-shadow:0 18px 42px rgba(11,36,80,.06)}.orvia-trust-panel__card{min-height:154px;padding:20px;display:flex;align-items:center;gap:14px;border-right:1px solid #dce4eb;background:#fff;color:#172033;text-decoration:none}.orvia-trust-panel__card:last-child{border-right:0}.orvia-trust-panel__icon{width:48px;height:48px;border-radius:14px;background:#eef5fa;display:grid;place-items:center;color:#0B2450;flex:0 0 auto}.orvia-trust-panel__card>div{display:grid;gap:5px}.orvia-trust-panel__card strong{font-size:14px;color:#071f3f}.orvia-trust-panel__card span,.orvia-trust-panel__card a{font-size:12px;color:#667085}.orvia-trust-panel__card img{width:62px;max-height:62px;object-fit:contain}.orvia-filing-disclosure{margin-top:2px}.orvia-filing-disclosure summary{cursor:pointer;font-size:11px;font-weight:800;color:#0B2450;list-style:none}.orvia-filing-disclosure summary:after{content:"  ▾"}.orvia-filing-disclosure[open] summary:after{content:"  ▴"}.orvia-filing-disclosure p{margin:8px 0 0;padding:9px 10px;border-left:3px solid #EAAA00;background:#fff8e8;color:#4b5563;font-size:11px;line-height:1.5}
  .orvia-legal-v1{font-family:Arial,Helvetica,sans-serif;border-top:1px solid rgba(11,36,80,.14);margin-top:18px;padding:18px 0 0;font-size:12px;line-height:1.55}.orvia-legal-v1__facts,.orvia-legal-v1__policies{display:flex;gap:10px 16px;flex-wrap:wrap;align-items:center}.orvia-legal-v1__policies{margin-top:9px}
  @media(max-width:980px){.orvia-estate-v1__mega{grid-template-columns:repeat(2,1fr)}.orvia-trust-panel__grid{grid-template-columns:repeat(2,1fr)}.orvia-trust-panel__card{border-bottom:1px solid #dce4eb}}@media(max-width:700px){.orvia-estate-v1__inner{flex-wrap:wrap}.orvia-estate-v1__push{margin-left:0;width:100%}.orvia-estate-v1__mega{grid-template-columns:1fr;position:fixed;left:18px;right:18px;top:54px;width:auto;max-height:70vh;overflow:auto}.orvia-trust-panel__grid{grid-template-columns:1fr}.orvia-trust-panel__card{border-right:0!important;min-height:auto}}
  `;document.head.appendChild(s);
  const groupHtml=products.map(([g,items])=>`<section><small>${g}</small>${items.map(([l,h])=>`<a href="${h}">${l}</a>`).join('')}</section>`).join('');
  const bar=document.createElement('div');bar.className='orvia-estate-v1';bar.innerHTML=`<div class="orvia-estate-v1__inner"><a class="orvia-estate-v1__brand" href="https://orvia.org.uk">ORVIA</a><details><summary>Explore ORVIA</summary><div class="orvia-estate-v1__mega">${groupHtml}</div></details><a href="https://orvia.org.uk/about">About</a><a href="https://orvia.org.uk/trust">Trust</a><span class="orvia-estate-v1__product">ORVIA Foundation</span><div class="orvia-estate-v1__push"><a href="https://orviafoundation.org.uk">This product</a></div></div>`;document.body.insertBefore(bar,document.body.firstChild);
  const footer=document.querySelector('footer');
  if(footer&&!document.querySelector('[data-orvia-trust-panel]')){const trust=document.createElement('section');trust.className='orvia-trust-panel';trust.dataset.orviaTrustPanel='1';trust.innerHTML=`<div class="orvia-trust-panel__inner"><div class="orvia-trust-panel__intro"><div class="orvia-trust-panel__eyebrow">TRUST SHOULD BE INSPECTABLE</div><h2>Do not take the claim on faith. Check the evidence.</h2><p>Company identity and external recognition are kept separate so you can see what each trust signal actually means.</p></div><div class="orvia-trust-panel__grid"><article class="orvia-trust-panel__card"><span class="orvia-trust-panel__icon">▦</span><div><strong>ORVIA Oversight Ltd</strong><a href="https://find-and-update.company-information.service.gov.uk/company/16123685" target="_blank" rel="noopener">Companies House 16123685</a><details class="orvia-filing-disclosure"><summary>Filing status</summary><p>Our first accounts are overdue. We are aware of the delay and are currently reconciling and preparing the accounts for filing. This is being treated as a priority, and this notice will be updated once the filing has been completed.</p></details></div></article><article class="orvia-trust-panel__card"><span class="orvia-trust-panel__icon">⌂</span><div><strong>Registered office</strong><span>London EC2A 4NE</span></div></article><a class="orvia-trust-panel__card" href="https://www.armedforcescovenant.gov.uk/" target="_blank" rel="noopener"><img src="https://www2.rfca.org.uk/l/343221/2023-08-01/29vmw8d/343221/1690892429j2EYWZTW/AFC_POSITIVE_RGB.png" alt="Armed Forces Covenant"><div><strong>Armed Forces Covenant</strong><span>Signatory</span></div></a><div class="orvia-trust-panel__card"><img src="https://www.dgt.nhs.uk/application/files/2716/4320/3669/AFC_RECOG_BRONZE_POS_RGB.PNG" alt="Employer Recognition Scheme Bronze Award"><div><strong>ERS Bronze</strong><span>Employer Recognition Scheme</span></div></div><a class="orvia-trust-panel__card" href="https://www.trustaveteran.com/team/orvia" target="_blank" rel="noopener"><span class="orvia-trust-panel__icon">★</span><div><strong>Trust A Veteran</strong><span>Current public profile</span></div></a></div></div>`;footer.parentNode.insertBefore(trust,footer);}
  if(footer&&!footer.querySelector('[data-orvia-legal-v1]')){const wrap=document.createElement('div');wrap.className='orvia-legal-v1';wrap.dataset.orviaLegalV1='1';wrap.innerHTML=`<div class="orvia-legal-v1__facts"><strong>ORVIA Oversight Ltd</strong><span>Company 16123685</span><span>Registered in England and Wales</span><span>3rd Floor, 86–90 Paul Street, London EC2A 4NE</span><a href="tel:03300433703">0330 043 3703</a><a href="mailto:hello@orvia.org.uk">hello@orvia.org.uk</a><a href="https://orvia.org.uk">orvia.org.uk</a></div><div class="orvia-legal-v1__policies"><a href="https://orvia.org.uk/privacy">Privacy</a><a href="https://orvia.org.uk/terms">Terms</a><a href="https://orvia.org.uk/cookies">Cookies</a><a href="https://orvia.org.uk/accessibility">Accessibility</a></div>`; (footer.querySelector('.shell,.wrap')||footer).appendChild(wrap);}
})();